In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
from src.data_loader import load_data

In [6]:
rating , movies= load_data("../data/")

In [7]:
rating.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [8]:
from src.matrix_factorization import train_svd_model
model, testset  = train_svd_model(rating)

In [10]:
from src.evaluation import evaluate_model
evaluate_model(model, testset)

0.8808746709977849

In [11]:
from src.recommender import get_top_n_recommendations

In [12]:
top_movies = get_top_n_recommendations(user_id=5, model=model, ratings=rating,movies=movies, n=5)
top_movies

,movieId,predicted_rating,title,genres
0,2959,4.314013,Fight Club (1999),Action|Crime|Drama|Thriller
1,1945,4.304767,On the Waterfront (1954),Crime|Drama
2,750,4.301058,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy|War
3,58559,4.299069,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
4,2028,4.289020,Saving Private Ryan (1998),Action|Drama|War

In [13]:
import pickle

In [15]:
from src.model_utils import save_model, load_model

In [16]:
save_model(model, "../models/svd_model.pkl")

In [18]:
model_load = load_model("../models/svd_model.pkl")

In [22]:
ppred= model_load.predict(1,50)

In [23]:
ppred.est

4.786346268347597